services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./database/db:/var/lib/postgresql/data
    ports:
      - 5439:5432

    environment:
      - POSTGRES_DB=nodebase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
